version: "3.8"

services:
  backend:
    image: "${REGISTRY_LOGIN_SERVER}/backend:latest"
    environment:
      - REGISTRY_LOGIN_SERVER=${REGISTRY_LOGIN_SERVER}
      - PORT=8080
    ports:
      - "8080:8080"
    restart: on-failure


  frontend:
    image: "${REGISTRY_LOGIN_SERVER}/frontend:latest"
    environment:
      - REGISTRY_LOGIN_SERVER=${REGISTRY_LOGIN_SERVER}
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure

      #grafana:
      # image: grafana/grafana
      #environment:
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      #- GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      # GF_SECURITY_ADMIN_PASSWORD=admin
    #volumes:
    #  - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    #ports:
    #  - "3000:3000"