version: "3.8"

services:
  backend:
    image: "${REGISTRY_LOGIN_SERVER}/backend:latest"
    environment:
      - PORT=8080
    restart: on-failure
    depends_on:
      - frontend


  frontend:
    image: "${REGISTRY_LOGIN_SERVER}/frontend:latest"
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure

  #prometheus:
   # image: prom/prometheus
    #volumes:
     # - ./prometheus.yml:/etc/prometheus/prometheus.yml
    #ports:
     # - "9090:9090"

      #grafana:
      # image: grafana/grafana
      #environment:
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      #- GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      # GF_SECURITY_ADMIN_PASSWORD=admin
    #volumes:
    #  - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    #ports:
    #  - "3000:3000"