version: "3.8"

services:
  backend:
    build:
      context: backend
    restart: on-failure
    environment:
      - PORT=8080

  frontend:
    build:
      context: frontend
    restart: on-failure
    ports:
      - "4040:80"
