version: "3.8"

services:
  backend:
    image: "${REGISTRY_LOGIN_SERVER}/backend:latest"
    environment:
      - PORT=8080
    restart: on-failure
    depends_on:
      - frontend


  frontend:
    image: "${REGISTRY_LOGIN_SERVER}/frontend:latest"
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure

  prometheus:
    image: "${REGISTRY_LOGIN_SERVER}/prometheus:latest"
    restart: on-failure
    depends_on:
      - backend