spring:
  application:
    name: backend

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  prometheus:
    metrics:
      export:
        enabled: true

  endpoint:
    health:
      show:
        details: always