name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Wrapper Verification
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        working-directory: ./backend
        run: ./gradlew build

      - name: Test
        working-directory: ./backend
        run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push Docker Images
        run: |
          docker compose -f docker-compose.yml build